import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "kaspi-115777748",
    slug: "lulu-flowers-15-roses-50",
    shopId: "kaspi-market",
    title: "LULU flowers: 15 роз, 50 см",
    description: "Моно-букет 15 роз 50 см, оформление. Источник Kaspi Market.",
    price: 9099,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "роза", quantity: 15 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h4a/h22/84840235565086.jpg?format=preview-large"],
    rating: { value: 4.6, count: 24 },
    isAvailable: true,
  },
  {
    id: "kaspi-112196579",
    slug: "cvetykz-25-roses-50",
    shopId: "kaspi-market",
    title: "CvetyKz: 25 роз, 50 см",
    description: "Моно-букет 25 роз 50 см, оформление. Источник Kaspi Market.",
    price: 14197,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "роза", quantity: 25 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h29/h3b/82358447767582.jpg?format=preview-large"],
    rating: { value: 4.5, count: 18 },
    isAvailable: true,
  },
  {
    id: "kaspi-129928936",
    slug: "gauhar-11-roses-60",
    shopId: "kaspi-market",
    title: "Гаухар: 11 роз, 60 см",
    description: "Моно-букет 11 роз 60 см, микс, с открыткой. Источник Kaspi Market.",
    price: 8399,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза", quantity: 11 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pf1/p51/7918222.png?format=preview-large"],
    rating: { value: 4.5, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-129847693",
    slug: "nuri-floral-19-spray-roses-70",
    shopId: "kaspi-market",
    title: "Nuri Floral: 19 кустовых роз, 70 см",
    description: "Яркий букет из кустовых роз 70 см, оформление. Источник Kaspi Market.",
    price: 20162,
    hasDiscount: false,
    flowersCount: 19,
    composition: [{ flowerType: "роза кустовая", quantity: 19 }],
    colors: ["pink"],
    stemHeights: [70],
    flowerTypes: ["роза кустовая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p3e/p23/7642998.jpeg?format=preview-large"],
    rating: { value: 4.7, count: 21 },
    isAvailable: true,
  },
  {
    id: "kaspi-116575899",
    slug: "hochu-buket-basket-37mix-50",
    shopId: "kaspi-market",
    title: "Хочу Букет: корзина 37 шт микс",
    description: "Композиция в корзине: гортензия, роза, хризантема, лизиантус, эвкалипт. Источник Kaspi Market.",
    price: 31259,
    hasDiscount: false,
    flowersCount: 37,
    composition: [
      { flowerType: "гортензия", quantity: 5 },
      { flowerType: "роза", quantity: 12 },
      { flowerType: "хризантема", quantity: 8 },
      { flowerType: "эустома", quantity: 6 },
      { flowerType: "эвкалипт", quantity: 6 },
    ],
    colors: ["pink", "white", "green"],
    stemHeights: [50],
    flowerTypes: ["роза классическая", "хризантема", "гортензия", "эустома"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h2a/h8c/85154073051166.jpg?format=preview-large"],
    rating: { value: 4.8, count: 19 },
    isAvailable: true,
  },
  {
    id: "kaspi-136482001",
    slug: "basket-7-roses-50",
    shopId: "kaspi-market",
    title: "Корзина: 7 роз, 50 см",
    description: "Композиция в корзине, 7 роз 50 см. Источник Kaspi Market.",
    price: 4896,
    hasDiscount: false,
    flowersCount: 7,
    composition: [{ flowerType: "роза", quantity: 7 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p2b/p5d/30742596.jpeg?format=preview-large"],
    rating: { value: 4.3, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-147133339",
    slug: "chrysanthemum-15-branches",
    shopId: "kaspi-market",
    title: "15 веток хризантемы",
    description: "Моно букет хризантемы, 15 веток. Источник Kaspi Market.",
    price: 14548,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "хризантема", quantity: 15 }],
    colors: ["white"],
    stemHeights: [60],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p1a/p3e/69807880.jpeg?format=preview-large"],
    rating: { value: 4.6, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-105135064",
    slug: "gauhar-9-roses-60",
    shopId: "kaspi-market",
    title: "Гаухар: 9 роз, 60 см",
    description: "Моно-букет 9 роз 60 см, оформление. Источник Kaspi Market.",
    price: 6492,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h68/h86/65108325662750.jpg?format=preview-large"],
    rating: { value: 4.4, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-116138198",
    slug: "tansholpan-11-roses-55",
    shopId: "kaspi-market",
    title: "Tansholpan: 11 роз, 55 см",
    description: "Моно-букет 11 роз 55 см в сумке. Источник Kaspi Market.",
    price: 7360,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза", quantity: 11 }],
    colors: ["pink"],
    stemHeights: [55],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hcd/hff/84991690899486.jpg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-110138207",
    slug: "mir-tsvetov-15-roses-50",
    shopId: "kaspi-market",
    title: "Мир Цветов: 15 роз, 50 см",
    description: "Моно-букет 15 роз 50 см. Источник Kaspi Market.",
    price: 12989,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "роза", quantity: 15 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hbb/h88/80561939218462.jpg?format=preview-large"],
    rating: { value: 4.6, count: 17 },
    isAvailable: true,
  },
  {
    id: "kaspi-111340379",
    slug: "box-15-roses-eucalyptus-50",
    shopId: "kaspi-market",
    title: "Коробка: 15 роз + эвкалипт",
    description: "Композиция в коробке: 15 роз, эвкалипт. Источник Kaspi Market.",
    price: 16974,
    hasDiscount: false,
    flowersCount: 15,
    composition: [
      { flowerType: "роза", quantity: 15 },
      { flowerType: "эвкалипт", quantity: 5 },
    ],
    colors: ["pink"],
    stemHeights: [50],
    flowerTypes: ["роза классическая", "эвкалипт"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h10/hea/81713028071454.jpg?format=preview-large"],
    rating: { value: 4.6, count: 13 },
    isAvailable: true,
  },
  {
    id: "kaspi-117493001",
    slug: "aurora-5-chrys-60",
    shopId: "kaspi-market",
    title: "Aurora: 5 хризантем, 60 см",
    description: "Моно-букет 5 хризантем 60 см, с открыткой. Источник Kaspi Market.",
    price: 4900,
    hasDiscount: false,
    flowersCount: 5,
    composition: [{ flowerType: "хризантема", quantity: 5 }],
    colors: ["white"],
    stemHeights: [60],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h94/hf4/85451593187358.jpg?format=preview-large"],
    rating: { value: 4.5, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-107927300",
    slug: "bant-flowers-7-roses-70",
    shopId: "kaspi-market",
    title: "Bant Flowers: 7 роз, 70 см",
    description: "Моно-букет 7 роз 70 см в оформлении. Источник Kaspi Market.",
    price: 7999,
    hasDiscount: false,
    flowersCount: 7,
    composition: [{ flowerType: "роза", quantity: 7 }],
    colors: ["red"],
    stemHeights: [70],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hc6/hb5/66589618602014.jpg?format=preview-large"],
    rating: { value: 4.5, count: 15 },
    isAvailable: true,
  },
  {
    id: "kaspi-143980210",
    slug: "basket-with-cake",
    shopId: "kaspi-market",
    title: "Корзина с тортиком",
    description: "Корзина с цветами и бенто-тортом. Источник Kaspi Market.",
    price: 14309,
    hasDiscount: false,
    flowersCount: 12,
    composition: [{ flowerType: "роза", quantity: 8 }, { flowerType: "хризантема", quantity: 4 }],
    colors: ["pink", "white"],
    stemHeights: [40],
    flowerTypes: ["роза классическая", "хризантема"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p46/p97/58193400.JPG?format=preview-large"],
    rating: { value: 4.4, count: 8 },
    isAvailable: true,
  },
  {
    id: "kaspi-116116131",
    slug: "floral-julieta-5-spray-50",
    shopId: "kaspi-market",
    title: "Floral: 5 кустовых пионовидных, 50 см",
    description: "Моно-букет 5 кустовых пионовидных роз 50 см с бенто-тортом. Источник Kaspi Market.",
    price: 13948,
    hasDiscount: false,
    flowersCount: 5,
    composition: [{ flowerType: "роза пионовидная", quantity: 5 }],
    colors: ["pink"],
    stemHeights: [50],
    flowerTypes: ["роза пионовидная"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hc7/ha6/84987790950430.jpg?format=preview-large"],
    rating: { value: 4.6, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-115229319",
    slug: "dream-flowers-box-11-roses-50",
    shopId: "kaspi-market",
    title: "Dream Flowers: коробка 11 роз, 50 см",
    description: "Композиция в коробке 11 роз 50 см + бенто-торт. Источник Kaspi Market.",
    price: 13697,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза", quantity: 11 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h13/h9c/84684907151390.jpg?format=preview-large"],
    rating: { value: 4.5, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-145462346",
    slug: "cvetasto-basket-spray-rose-cake",
    shopId: "kaspi-market",
    title: "Cvetasto: корзина кустовая роза + торт",
    description: "Корзина с кустовой розой и бенто-тортом в подарок. Источник Kaspi Market.",
    price: 12484,
    hasDiscount: false,
    flowersCount: 3,
    composition: [{ flowerType: "роза кустовая", quantity: 3 }],
    colors: ["pink"],
    stemHeights: [30],
    flowerTypes: ["роза кустовая"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p6f/p92/64504865.png?format=preview-large"],
    rating: { value: 4.4, count: 7 },
    isAvailable: true,
  },
  {
    id: "kaspi-119002136",
    slug: "chrys-9-60-card",
    shopId: "kaspi-market",
    title: "9 хризантем 60 см с открыткой",
    description: "Моно-букет 9 хризантем 60 см с открыткой. Источник Kaspi Market.",
    price: 8998,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "хризантема", quantity: 9 }],
    colors: ["white"],
    stemHeights: [60],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h64/h37/85908328218654.jpg?format=preview-large"],
    rating: { value: 4.6, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-122934494",
    slug: "bag-3-chrys-20",
    shopId: "kaspi-market",
    title: "Сумочка: 3 хризантемы, 20 см",
    description: "Композиция с открыткой: 3 хризантемы, 20 см. Источник Kaspi Market.",
    price: 2999,
    hasDiscount: false,
    flowersCount: 3,
    composition: [{ flowerType: "хризантема", quantity: 3 }],
    colors: ["white"],
    stemHeights: [20],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/he4/h1e/86958847229982.jpg?format=preview-large"],
    rating: { value: 4.3, count: 6 },
    isAvailable: true,
  },
  {
    id: "kaspi-113267626",
    slug: "floralux-11-roses-strawberry",
    shopId: "kaspi-market",
    title: "FloraLux: 11 роз + сладости",
    description: "Комбо: 11 роз 50 см + клубника в шоколаде. Источник Kaspi Market.",
    price: 9990,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза", quantity: 11 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "chocolate", title: "Клубника в шоколаде" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h57/h4a/83707706966046.jpg?format=preview-large"],
    rating: { value: 4.6, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-110106403",
    slug: "korkem-101-roses-60",
    shopId: "kaspi-market",
    title: "Korkem Gulderi: 101 роза, 60 см",
    description: "Моно-букет 101 роза 60 см. Источник Kaspi Market.",
    price: 30990,
    hasDiscount: false,
    flowersCount: 101,
    composition: [{ flowerType: "роза", quantity: 101 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h97/h52/80524795281438.jpg?format=preview-large"],
    rating: { value: 4.7, count: 22 },
    isAvailable: true,
  },
  {
    id: "kaspi-110106446",
    slug: "domik-51-roses-100",
    shopId: "kaspi-market",
    title: "Цветочный Домик: 51 роза, 100 см",
    description: "Моно-букет 51 роза 100 см. Источник Kaspi Market.",
    price: 31993,
    hasDiscount: false,
    flowersCount: 51,
    composition: [{ flowerType: "роза", quantity: 51 }],
    colors: ["red"],
    stemHeights: [100],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h49/h42/80524795838494.jpg?format=preview-large"],
    rating: { value: 4.7, count: 25 },
    isAvailable: true,
  },
  {
    id: "kaspi-122049425",
    slug: "podarkoff-25-roses-60-berries",
    shopId: "kaspi-market",
    title: "Podarkoff: 25 роз + ягоды",
    description: "Комбо: 25 роз 60 см + клубника в шоколаде. Источник Kaspi Market.",
    price: 16999,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "роза", quantity: 25 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "chocolate", title: "Клубника в шоколаде" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hee/h31/86692251533342.jpg?format=preview-large"],
    rating: { value: 4.6, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-115229296",
    slug: "dream-flowers-13-roses-raffaello",
    shopId: "kaspi-market",
    title: "Dream Flowers: 13 роз + рафаэлло",
    description: "Комбо: 13 роз 50 см + Raffaello. Источник Kaspi Market.",
    price: 14900,
    hasDiscount: false,
    flowersCount: 13,
    composition: [{ flowerType: "роза", quantity: 13 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "chocolate", title: "Raffaello" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h99/h1e/84685139116062.jpg?format=preview-large"],
    rating: { value: 4.5, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-117191211",
    slug: "spray-11-roses-50",
    shopId: "kaspi-market",
    title: "Кустовые розы: 11 шт, 50 см",
    description: "Моно-букет кустовых роз 11 шт, 50 см. Источник Kaspi Market.",
    price: 12000,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза кустовая", quantity: 11 }],
    colors: ["pink"],
    stemHeights: [50],
    flowerTypes: ["роза кустовая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/he8/ha2/85353857384478.jpg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-113326108",
    slug: "flowers-center-astana-101-roses-60",
    shopId: "kaspi-market",
    title: "Flowers Center: 101 роза, 60 см",
    description: "Моно-букет 101 эквадорская роза 60 см. Источник Kaspi Market.",
    price: 32900,
    hasDiscount: false,
    flowersCount: 101,
    composition: [{ flowerType: "роза", quantity: 101 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hd1/h77/83785640706078.jpg?format=preview-large"],
    rating: { value: 4.7, count: 26 },
    isAvailable: true,
  },
  {
    id: "kaspi-110857859",
    slug: "gulim-flowers-18-mix-50",
    shopId: "kaspi-market",
    title: "Gulim: микс 18 шт",
    description: "Букет: кустовая пионовидная роза, эвкалипт, диантус. Источник Kaspi Market.",
    price: 18478,
    hasDiscount: false,
    flowersCount: 18,
    composition: [
      { flowerType: "роза пионовидная", quantity: 9 },
      { flowerType: "эвкалипт", quantity: 4 },
      { flowerType: "диантус", quantity: 5 },
    ],
    colors: ["pink", "white"],
    stemHeights: [50],
    flowerTypes: ["роза пионовидная", "эвкалипт", "гвоздика"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h0c/h08/81273658671134.jpg?format=preview-large"],
    rating: { value: 4.6, count: 16 },
    isAvailable: true,
  },
  {
    id: "kaspi-116575840",
    slug: "hochu-buket-5-roses-40",
    shopId: "kaspi-market",
    title: "Хочу Букет: 5 роз, 40 см",
    description: "Моно-букет 5 роз 40 см. Источник Kaspi Market.",
    price: 4500,
    hasDiscount: false,
    flowersCount: 5,
    composition: [{ flowerType: "роза", quantity: 5 }],
    colors: ["red"],
    stemHeights: [40],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h17/hdb/85154999304222.jpg?format=preview-large"],
    rating: { value: 4.4, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-113326105",
    slug: "flowers-center-51-roses-60",
    shopId: "kaspi-market",
    title: "Flowers Center: 51 роза, 60 см",
    description: "Моно-букет 51 эквадорская роза 60 см. Источник Kaspi Market.",
    price: 24990,
    hasDiscount: false,
    flowersCount: 51,
    composition: [{ flowerType: "роза", quantity: 51 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h1a/h74/83784728182814.jpg?format=preview-large"],
    rating: { value: 4.7, count: 23 },
    isAvailable: true,
  },
  {
    id: "kaspi-119348652",
    slug: "chic-flowers-8-mix-50",
    shopId: "kaspi-market",
    title: "Chic: 8 шт микс (гортензия, роза)",
    description: "Букет с открыткой: гортензия, роза, 8 шт 50 см. Источник Kaspi Market.",
    price: 8888,
    hasDiscount: false,
    flowersCount: 8,
    composition: [
      { flowerType: "гортензия", quantity: 2 },
      { flowerType: "роза", quantity: 6 },
    ],
    colors: ["pink", "white"],
    stemHeights: [50],
    flowerTypes: ["гортензия", "роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h3e/h47/86001347395614.jpg?format=preview-large"],
    rating: { value: 4.5, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-118282171",
    slug: "chic-flowers-bento-mix-5-50",
    shopId: "kaspi-market",
    title: "Chic: бенто-комбо, 5 шт",
    description: "Букет + бенто-торт: гортензия, роза, хризантема, 5 шт 50 см. Источник Kaspi Market.",
    price: 10490,
    hasDiscount: false,
    flowersCount: 5,
    composition: [
      { flowerType: "гортензия", quantity: 1 },
      { flowerType: "роза", quantity: 3 },
      { flowerType: "хризантема", quantity: 1 },
    ],
    colors: ["pink", "white"],
    stemHeights: [50],
    flowerTypes: ["гортензия", "роза классическая", "хризантема"],
    gifts: [{ type: "cake", title: "Бенто-торт" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hb7/h64/85700049731614.jpg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-112183152",
    slug: "gulim-25-roses-60-cake",
    shopId: "kaspi-market",
    title: "Gulim: 25 роз + бенто",
    description: "Моно-букет 25 роз 60 см с бенто-тортом. Источник Kaspi Market.",
    price: 15499,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "роза", quantity: 25 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "cake", title: "Бенто-торт" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hc2/h29/82343602192414.jpg?format=preview-large"],
    rating: { value: 4.6, count: 15 },
    isAvailable: true,
  },
  {
    id: "kaspi-120335063",
    slug: "talan-flowers-25-roses-50",
    shopId: "kaspi-market",
    title: "Talan: 25 роз, 50 см",
    description: "Моно-букет 25 роз 50 см. Источник Kaspi Market.",
    price: 13577,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "роза", quantity: 25 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h9d/h1f/86263513382942.jpg?format=preview-large"],
    rating: { value: 4.5, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-113326107",
    slug: "flowers-center-51-roses-60-b",
    shopId: "kaspi-market",
    title: "Flowers Center: 51 роза, 60 см (вариант B)",
    description: "Моно-букет 51 роза 60 см, вариант карточки B. Источник Kaspi Market.",
    price: 24275,
    hasDiscount: false,
    flowersCount: 51,
    composition: [{ flowerType: "роза", quantity: 51 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h7d/h28/83785671147550.jpg?format=preview-large"],
    rating: { value: 4.7, count: 21 },
    isAvailable: true,
  },
  {
    id: "kaspi-135925698",
    slug: "box-3-chrys-15",
    shopId: "kaspi-market",
    title: "Коробка: 3 хризантемы, 15 см",
    description: "Композиция в оформлении: 3 хризантемы, 15 см. Источник Kaspi Market.",
    price: 2999,
    hasDiscount: false,
    flowersCount: 3,
    composition: [{ flowerType: "хризантема", quantity: 3 }],
    colors: ["white"],
    stemHeights: [15],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pe4/p89/28821825.jpg?format=preview-large"],
    rating: { value: 4.3, count: 6 },
    isAvailable: true,
  },
  {
    id: "kaspi-143756562",
    slug: "oda-9-roses-eucalyptus-60",
    shopId: "kaspi-market",
    title: "O, DA!: 9 роз + эвкалипт",
    description: "Букет 9 роз 60 см с эвкалиптом. Источник Kaspi Market.",
    price: 9130,
    hasDiscount: false,
    flowersCount: 9,
    composition: [
      { flowerType: "роза", quantity: 9 },
      { flowerType: "эвкалипт", quantity: 3 },
    ],
    colors: ["pink"],
    stemHeights: [60],
    flowerTypes: ["роза классическая", "эвкалипт"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pe5/paa/57434048.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-119128447",
    slug: "eywa-flowers-21-spray-peony-rose-40",
    shopId: "kaspi-market",
    title: "Eywa: 21 кустовая/пионовидная роза, 40 см",
    description: "Композиция в кашпо из кустовых и пионовидных роз, 21 шт, 40 см. Источник Kaspi Market.",
    price: 25998,
    hasDiscount: false,
    flowersCount: 21,
    composition: [
      { flowerType: "роза кустовая", quantity: 11 },
      { flowerType: "роза пионовидная", quantity: 10 },
    ],
    colors: ["pink"],
    stemHeights: [40],
    flowerTypes: ["роза кустовая", "роза пионовидная"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h3c/hec/85952344293406.jpg?format=preview-large"],
    rating: { value: 4.6, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-148154677",
    slug: "chrysanthemum-15-branches-50",
    shopId: "kaspi-market",
    title: "15 веток хризантемы",
    description: "Моно букет хризантем, 15 веток. Источник Kaspi Market.",
    price: 14895,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "хризантема", quantity: 15 }],
    colors: ["white"],
    stemHeights: [50],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p77/p02/73122858.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-135065090",
    slug: "flowers-center-29-spray-peony-70",
    shopId: "kaspi-market",
    title: "Flowers Center: 29 кустовых пионовидных, 70 см",
    description: "Моно-букет 29 кустовых пионовидных роз 70 см. Источник Kaspi Market.",
    price: 29817,
    hasDiscount: false,
    flowersCount: 29,
    composition: [{ flowerType: "роза пионовидная", quantity: 29 }],
    colors: ["pink"],
    stemHeights: [70],
    flowerTypes: ["роза пионовидная"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p54/p56/26052070.jpeg?format=preview-large"],
    rating: { value: 4.6, count: 18 },
    isAvailable: true,
  },
  {
    id: "kaspi-101465702",
    slug: "gauhar-9-roses-60-pink",
    shopId: "kaspi-market",
    title: "Гаухар: 9 роз, 60 см",
    description: "Моно-букет 9 роз 60 см в оформлении. Источник Kaspi Market.",
    price: 7499,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["pink"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/he8/hf6/64345125388318.jpg?format=preview-large"],
    rating: { value: 4.5, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-118000180",
    slug: "bento-9-roses-50",
    shopId: "kaspi-market",
    title: "Бенто комбо: 9 роз, 50 см",
    description: "Моно-букет 9 роз 50 см с бенто-тортом. Источник Kaspi Market.",
    price: 14893,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h9f/hf0/85609191211038.jpg?format=preview-large"],
    rating: { value: 4.6, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-139321293",
    slug: "chrys-15-box-50",
    shopId: "kaspi-market",
    title: "Композиция: 15 хризантем, 50 см",
    description: "Композиция с открыткой, 15 хризантем 50 см. Источник Kaspi Market.",
    price: 21498,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "хризантема", quantity: 15 }],
    colors: ["white"],
    stemHeights: [50],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p95/pe4/41072024.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-120041575",
    slug: "pink-rose-11-50",
    shopId: "kaspi-market",
    title: "Pink Rose: 11 белых роз, 50 см",
    description: "Моно-букет 11 белых роз 50 см с открыткой. Источник Kaspi Market.",
    price: 11899,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза", quantity: 11 }],
    colors: ["white"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/he6/hcb/86190376878110.jpg?format=preview-large"],
    rating: { value: 4.5, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-111216851",
    slug: "hochu-buket-basket-18-mix-40",
    shopId: "kaspi-market",
    title: "Хочу Букет: корзина 18 шт микс",
    description: "Корзина: роза, хризантема, кустовая роза, эвкалипт, 18 шт, 40 см. Источник Kaspi Market.",
    price: 28995,
    hasDiscount: false,
    flowersCount: 18,
    composition: [
      { flowerType: "роза", quantity: 6 },
      { flowerType: "хризантема", quantity: 4 },
      { flowerType: "роза кустовая", quantity: 4 },
      { flowerType: "эвкалипт", quantity: 4 },
    ],
    colors: ["pink", "white", "green"],
    stemHeights: [40],
    flowerTypes: ["роза классическая", "хризантема", "роза кустовая", "эвкалипт"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/had/hfe/81546069901342.jpg?format=preview-large"],
    rating: { value: 4.6, count: 13 },
    isAvailable: true,
  },
  {
    id: "kaspi-112780675",
    slug: "floral-box-9-roses-40",
    shopId: "kaspi-market",
    title: "Floral: коробка 9 роз, 40 см",
    description: "Композиция в коробке: 9 роз 40 см. Источник Kaspi Market.",
    price: 11396,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["pink"],
    stemHeights: [40],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h8d/h7c/83067403436062.jpg?format=preview-large"],
    rating: { value: 4.5, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-106595518",
    slug: "gauhar-21-roses-gypsophila-60",
    shopId: "kaspi-market",
    title: "Гаухар: 21 роза + гипсофила, 60 см",
    description: "Букет 21 роза 60 см с гипсофилой и рускусом. Источник Kaspi Market.",
    price: 19888,
    hasDiscount: false,
    flowersCount: 21,
    composition: [
      { flowerType: "роза", quantity: 21 },
      { flowerType: "гипсофила", quantity: 3 },
      { flowerType: "рускус", quantity: 3 },
    ],
    colors: ["red", "white", "green"],
    stemHeights: [60],
    flowerTypes: ["роза классическая", "гипсофила"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h96/h1d/64443408613406.jpg?format=preview-large"],
    rating: { value: 4.6, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-113225257",
    slug: "gulim-7-roses-50-cake",
    shopId: "kaspi-market",
    title: "Gulim: 7 роз 50 см + бенто",
    description: "Моно-букет 7 роз 50 см с бенто-тортом. Источник Kaspi Market.",
    price: 14820,
    hasDiscount: false,
    flowersCount: 7,
    composition: [{ flowerType: "роза", quantity: 7 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h24/hd6/83655848132638.jpg?format=preview-large"],
    rating: { value: 4.6, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-119003870",
    slug: "nazdar-5-spray-roses-60",
    shopId: "kaspi-market",
    title: "Nazdar: 5 кустовых роз, 60 см",
    description: "Букет: 5 кустовых роз 60 см с эвкалиптом. Источник Kaspi Market.",
    price: 10000,
    hasDiscount: false,
    flowersCount: 5,
    composition: [{ flowerType: "роза кустовая", quantity: 5 }],
    colors: ["pink"],
    stemHeights: [60],
    flowerTypes: ["роза кустовая", "эвкалипт"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h7c/hc7/85914427621406.jpg?format=preview-large"],
    rating: { value: 4.5, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-139374247",
    slug: "charmdeco-hydrangea-set",
    shopId: "kaspi-market",
    title: "Charmdeco: сет с гортензией и шоколадом",
    description: "Подарочный сет: гортензия 3 шт 60 см + шоколад Merci. Источник Kaspi Market.",
    price: 21500,
    hasDiscount: false,
    flowersCount: 3,
    composition: [{ flowerType: "гортензия", quantity: 3 }],
    colors: ["blue"],
    stemHeights: [60],
    flowerTypes: ["гортензия"],
    gifts: [{ type: "chocolate", title: "Merci" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p5d/pd0/41243791.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 8 },
    isAvailable: true,
  },
  {
    id: "kaspi-141865637",
    slug: "chrysanthemum-7-50",
    shopId: "kaspi-market",
    title: "Букет хризантем: 7 шт, 50 см",
    description: "Моно-букет хризантем 7 шт 50 см. Источник Kaspi Market.",
    price: 8000,
    hasDiscount: false,
    flowersCount: 7,
    composition: [{ flowerType: "хризантема", quantity: 7 }],
    colors: ["white"],
    stemHeights: [50],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pc5/p50/50694241.jpg?format=preview-large"],
    rating: { value: 4.4, count: 8 },
    isAvailable: true,
  },
  {
    id: "kaspi-143231990",
    slug: "lui-buton-klassicheskiy",
    shopId: "kaspi-market",
    title: "LUI BUTON: букет \"Классический\"",
    description: "Классический букет в оформлении. Источник Kaspi Market.",
    price: 16600,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "роза", quantity: 15 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p44/pff/55577580.jpg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-135737866",
    slug: "flowerkz-25-spray-50",
    shopId: "kaspi-market",
    title: "Flower.kz: 25 кустовых, 50 см",
    description: "Моно-букет 25 кустовых роз 50 см. Источник Kaspi Market.",
    price: 48200,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "роза кустовая", quantity: 25 }],
    colors: ["pink"],
    stemHeights: [50],
    flowerTypes: ["роза кустовая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pd6/p47/28177946.jpg?format=preview-large"],
    rating: { value: 4.6, count: 14 },
    isAvailable: true,
  },
  {
    id: "kaspi-139266155",
    slug: "alstroemeria-19-80",
    shopId: "kaspi-market",
    title: "19 альстромерий, 80 см",
    description: "Букет с открыткой: альстромерия 19 шт 80 см. Источник Kaspi Market.",
    price: 12590,
    hasDiscount: false,
    flowersCount: 19,
    composition: [{ flowerType: "альстромерия", quantity: 19 }],
    colors: ["multicolor"],
    stemHeights: [80],
    flowerTypes: ["альстромерия"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pee/p76/40867613.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-138257300",
    slug: "premium-rose-25-80",
    shopId: "kaspi-market",
    title: "Premium Rose: 25 роз, 80 см",
    description: "Моно-букет 25 роз 80 см. Источник Kaspi Market.",
    price: 22000,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "роза", quantity: 25 }],
    colors: ["red"],
    stemHeights: [80],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pf3/pc0/37214812.jpg?format=preview-large"],
    rating: { value: 4.6, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-118253361",
    slug: "chic-flowers-51-roses-100",
    shopId: "kaspi-market",
    title: "Chic: 51 роза, 100 см",
    description: "Моно-букет 51 роза 100 см с открыткой. Источник Kaspi Market.",
    price: 49898,
    hasDiscount: false,
    flowersCount: 51,
    composition: [{ flowerType: "роза", quantity: 51 }],
    colors: ["red"],
    stemHeights: [100],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h9c/h99/85692571025438.jpg?format=preview-large"],
    rating: { value: 4.7, count: 20 },
    isAvailable: true,
  },
  {
    id: "kaspi-116358306",
    slug: "rozykz-9-roses-50",
    shopId: "kaspi-market",
    title: "Rozy.kz: 9 красных роз, 50 см",
    description: "Букет из 9 красных роз 50 см. Источник Kaspi Market.",
    price: 11100,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h3c/h45/85066972168222.jpg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-115800296",
    slug: "sunflower-box-7-35",
    shopId: "kaspi-market",
    title: "Коробка: 7 подсолнухов, 35 см",
    description: "Композиция в коробке: 7 подсолнухов, 35 см. Источник Kaspi Market.",
    price: 48498,
    hasDiscount: false,
    flowersCount: 7,
    composition: [{ flowerType: "подсолнух", quantity: 7 }],
    colors: ["yellow"],
    stemHeights: [35],
    flowerTypes: ["подсолнух"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h5c/h46/84849200234526.jpg?format=preview-large"],
    rating: { value: 4.6, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-123761715",
    slug: "elit-5-roses-40",
    shopId: "kaspi-market",
    title: "Элит: 5 белых роз, 40 см",
    description: "Моно-букет 5 белых роз 40 см с открыткой. Источник Kaspi Market.",
    price: 4500,
    hasDiscount: false,
    flowersCount: 5,
    composition: [{ flowerType: "роза", quantity: 5 }],
    colors: ["white"],
    stemHeights: [40],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hc4/h4e/87172459462686.jpg?format=preview-large"],
    rating: { value: 4.4, count: 8 },
    isAvailable: true,
  },
  {
    id: "kaspi-139914595",
    slug: "blossom-21-peonies-50",
    shopId: "kaspi-market",
    title: "Blossom: 21 пион, 50 см",
    description: "Букет 21 пион 50 см. Источник Kaspi Market.",
    price: 26000,
    hasDiscount: false,
    flowersCount: 21,
    composition: [{ flowerType: "пион", quantity: 21 }],
    colors: ["pink"],
    stemHeights: [50],
    flowerTypes: ["пион"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pdc/p41/43156182.jpeg?format=preview-large"],
    rating: { value: 4.6, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-142364873",
    slug: "lui-buton-bento-spray",
    shopId: "kaspi-market",
    title: "LUI BUTON: бенто + кустовые розы",
    description: "Комбо: бенто-торт и букет кустовых роз. Источник Kaspi Market.",
    price: 27100,
    hasDiscount: false,
    flowersCount: 11,
    composition: [{ flowerType: "роза кустовая", quantity: 11 }],
    colors: ["pink"],
    stemHeights: [50],
    flowerTypes: ["роза кустовая"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p64/p7a/52514637.jpg?format=preview-large"],
    rating: { value: 4.6, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-148172877",
    slug: "chrys-25-branches",
    shopId: "kaspi-market",
    title: "25 веток хризантем",
    description: "Моно букет 25 веток хризантем. Источник Kaspi Market.",
    price: 30000,
    hasDiscount: false,
    flowersCount: 25,
    composition: [{ flowerType: "хризантема", quantity: 25 }],
    colors: ["white"],
    stemHeights: [60],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p52/pb9/73185448.jpeg?format=preview-large"],
    rating: { value: 4.6, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-136966621",
    slug: "pink-rose-9-60",
    shopId: "kaspi-market",
    title: "Pink Rose: 9 роз, 60 см",
    description: "Букет 9 роз 60 см. Источник Kaspi Market.",
    price: 8000,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["pink"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p12/p4b/32430329.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 9 },
    isAvailable: true,
  },
  {
    id: "kaspi-142873958",
    slug: "balflowers-9-roses-choco",
    shopId: "kaspi-market",
    title: "Balflowers: 9 роз + клубника в шоколаде",
    description: "Комбо букет 9 роз 60 см и клубника в шоколаде. Источник Kaspi Market.",
    price: 18056,
    hasDiscount: false,
    flowersCount: 9,
    composition: [{ flowerType: "роза", quantity: 9 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "chocolate", title: "Клубника в шоколаде" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p47/p47/54329427.jpeg?format=preview-large"],
    rating: { value: 4.6, count: 11 },
    isAvailable: true,
  },
  {
    id: "kaspi-144421249",
    slug: "floria-15-red-roses",
    shopId: "kaspi-market",
    title: "Floria.kz: 15 красных роз",
    description: "Моно-букет 15 красных роз. Источник Kaspi Market.",
    price: 16500,
    hasDiscount: false,
    flowersCount: 15,
    composition: [{ flowerType: "роза", quantity: 15 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/p4f/p6b/59795672.jpeg?format=preview-large"],
    rating: { value: 4.5, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-118249437",
    slug: "bento-7-roses-40",
    shopId: "kaspi-market",
    title: "Бенто комбо: 7 роз, 40 см",
    description: "Моно-букет 7 роз 40 см с бенто-тортом. Источник Kaspi Market.",
    price: 9998,
    hasDiscount: false,
    flowersCount: 7,
    composition: [{ flowerType: "роза", quantity: 7 }],
    colors: ["red"],
    stemHeights: [40],
    flowerTypes: ["роза классическая"],
    gifts: [
      { type: "cake", title: "Бенто-торт" },
      { type: "card", title: "Открытка" },
    ],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h12/hf1/85692659826718.jpg?format=preview-large"],
    rating: { value: 4.5, count: 10 },
    isAvailable: true,
  },
  {
    id: "kaspi-115032028",
    slug: "51-roses-40",
    shopId: "kaspi-market",
    title: "51 роза, 40 см",
    description: "Моно-букет 51 роза 40 см. Источник Kaspi Market.",
    price: 29550,
    hasDiscount: false,
    flowersCount: 51,
    composition: [{ flowerType: "роза", quantity: 51 }],
    colors: ["red"],
    stemHeights: [40],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/hc7/he2/84624180838430.jpg?format=preview-large"],
    rating: { value: 4.6, count: 18 },
    isAvailable: true,
  },
  {
    id: "kaspi-144564974",
    slug: "floria-royal-51-cake",
    shopId: "kaspi-market",
    title: "Floria.kz: Royal Set 51 роза + торт",
    description: "Комбо: 51 красная роза и торт. Источник Kaspi Market.",
    price: 49900,
    hasDiscount: false,
    flowersCount: 51,
    composition: [{ flowerType: "роза", quantity: 51 }],
    colors: ["red"],
    stemHeights: [60],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "cake", title: "Торт" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pcc/pdf/60316640.jpeg?format=preview-large"],
    rating: { value: 4.6, count: 16 },
    isAvailable: true,
  },
  {
    id: "kaspi-118254519",
    slug: "chic-flowers-21-roses-50",
    shopId: "kaspi-market",
    title: "Chic: композиция 21 роза, 50 см",
    description: "Композиция с открыткой, 21 роза 50 см. Источник Kaspi Market.",
    price: 16108,
    hasDiscount: false,
    flowersCount: 21,
    composition: [{ flowerType: "роза", quantity: 21 }],
    colors: ["red"],
    stemHeights: [50],
    flowerTypes: ["роза классическая"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/ha9/hcf/85691528970270.jpg?format=preview-large"],
    rating: { value: 4.6, count: 12 },
    isAvailable: true,
  },
  {
    id: "kaspi-140776741",
    slug: "rosabelle-5-chrys-40",
    shopId: "kaspi-market",
    title: "RosaBelle: 5 хризантем, 40 см",
    description: "Композиция с открыткой: 5 хризантем 40 см. Источник Kaspi Market.",
    price: 17000,
    hasDiscount: false,
    flowersCount: 5,
    composition: [{ flowerType: "хризантема", quantity: 5 }],
    colors: ["white"],
    stemHeights: [40],
    flowerTypes: ["хризантема"],
    gifts: [{ type: "card", title: "Открытка" }],
    images: ["https://resources.cdn-kaspi.kz/img/m/p/pfd/p23/46494784.jpeg?format=preview-large"],
    rating: { value: 4.4, count: 8 },
    isAvailable: true,
  },
];
