export type ReferenceOption = {
  value: string;
  label: string;
};

// Часто используемые типы цветов/растений для поиска и подсказок.
export const FLOWER_TYPE_OPTIONS: ReferenceOption[] = [
  { value: "роза классическая", label: "Роза (классическая)" },
  { value: "роза кустовая", label: "Роза кустовая" },
  { value: "роза спрей", label: "Роза спрей" },
  { value: "роза эквадорская", label: "Роза эквадорская" },
  { value: "роза пионовидная", label: "Роза пионовидная" },
  { value: "хризантема одноголовая", label: "Хризантема одноголовая" },
  { value: "хризантема кустовая", label: "Хризантема кустовая" },
  { value: "тюльпан", label: "Тюльпан" },
  { value: "лилия", label: "Лилия" },
  { value: "гвоздика", label: "Гвоздика" },
  { value: "альстромерия", label: "Альстромерия" },
  { value: "гербера", label: "Гербера" },
  { value: "эустома", label: "Эустома (лизиантус)" },
  { value: "гипсофила", label: "Гипсофила" },
  { value: "ирис", label: "Ирис" },
  { value: "гортензия", label: "Гортензия" },
  { value: "орхидея", label: "Орхидея" },
  { value: "ромашка", label: "Ромашка" },
  { value: "пион", label: "Пион" },
  { value: "астра", label: "Астра" },
  { value: "гладиолус", label: "Гладиолус" },
  { value: "калла", label: "Калла" },
  { value: "фрезия", label: "Фрезия" },
  { value: "антуриум", label: "Антуриум" },
  { value: "подсолнух", label: "Подсолнух" },
  { value: "лаванда", label: "Лаванда" },
  { value: "сирень", label: "Сирень" },
  { value: "камелия", label: "Камелия" },
  { value: "ранункулюс", label: "Ранункулюс" },
  { value: "статица", label: "Статица" },
];

// Набор цветов для фильтрации по палитре.
export const COLOR_OPTIONS: ReferenceOption[] = [
  { value: "white", label: "Белый" },
  { value: "black", label: "Чёрный" },
  { value: "red", label: "Красный" },
  { value: "pink", label: "Розовый" },
  { value: "yellow", label: "Жёлтый" },
  { value: "orange", label: "Оранжевый" },
  { value: "peach", label: "Персиковый" },
  { value: "cream", label: "Кремовый" },
  { value: "purple", label: "Фиолетовый" },
  { value: "lilac", label: "Лиловый" },
  { value: "blue", label: "Синий" },
  { value: "light-blue", label: "Голубой" },
  { value: "green", label: "Зелёный" },
  { value: "mint", label: "Мятный" },
  { value: "burgundy", label: "Бордовый" },
  { value: "coral", label: "Коралловый" },
  { value: "champagne", label: "Шампань" },
  { value: "salmon", label: "Лососёвый" },
  { value: "lavender", label: "Лавандовый" },
  { value: "multicolor", label: "Микс / разноцветный" },
];

export const STEM_HEIGHT_OPTIONS: ReferenceOption[] = [
  { value: "10", label: "10 см" },
  { value: "15", label: "15 см" },
  { value: "20", label: "20 см" },
  { value: "25", label: "25 см" },
  { value: "30", label: "30 см" },
  { value: "35", label: "35 см" },
  { value: "40", label: "40 см" },
  { value: "45", label: "45 см" },
  { value: "50", label: "50 см" },
  { value: "55", label: "55 см" },
  { value: "60", label: "60 см" },
  { value: "65", label: "65 см" },
  { value: "70", label: "70 см" },
  { value: "75", label: "75 см" },
  { value: "80", label: "80 см" },
  { value: "85", label: "85 см" },
  { value: "90", label: "90 см" },
  { value: "95", label: "95 см" },
  { value: "100", label: "100 см" },
  { value: "110", label: "110 см" },
  { value: "120", label: "120 см" },
  { value: "130", label: "130 см" },
  { value: "140", label: "140 см" },
  { value: "150", label: "150 см" },
  { value: "160", label: "160 см" },
  { value: "170", label: "170 см" },
  { value: "180", label: "180 см" },
  { value: "190", label: "190 см" },
  { value: "200", label: "200 см" },
  { value: "220", label: "220 см" },
];

